### ISSUE TITLE
README.MD is actually just a picture of beer

### ISSUE THREAD

**Issue by RickCarlino** [DataMelon/porter#1]
Hi,

I was trying to figure out what this repo does, but the README appears to be nothing more than a picture of dark beer. I'm not sure exactly, but I think it may be malt based.

**Comment by elbow-jason** [comment]
We must appeal to the masses.

**Comment by m3talsmith** [comment]
I massive quantities :wink:

**Comment by elbow-jason** [comment]
Fixed*

*It's no longer a picture of beer

**Comment by elbow-jason** [comment]
INVALID!!
